spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:19094}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

stats.kafka.user-actions-topic=stats.user-actions.v1
