server.port=8080

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/users/**

spring.cloud.gateway.routes[1].id=ewm-service
spring.cloud.gateway.routes[1].uri=lb://ewm-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**,/categories/**,/compilations/**,/users/**,/admin/events/**,/admin/categories/**,/admin/compilations/**,/admin/comments/**