services:

  discovery-server:
    build:
      context: .
      dockerfile: infra/discovery-server/Dockerfile
    ports:
      - "8761:8761"

  config-server:
    build:
      context: .
      dockerfile: infra/config-server/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    environment:
      SERVER_PORT: 8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/


  stats-db:
    image: postgres:17
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 10


  user-db:
    image: postgres:17
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users" ]
      interval: 5s
      timeout: 5s
      retries: 10


  request-db:
    image: postgres:17
    ports:
      - "6544:5432"
    environment:
      POSTGRES_DB: requests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - request-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d requests" ]
      interval: 5s
      timeout: 5s
      retries: 10


  event-db:
    image: postgres:17
    ports:
      - "6545:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - event-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d events" ]
      interval: 5s
      timeout: 5s
      retries: 10


  comment-db:
    image: postgres:17
    ports:
      - "6546:5432"
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - comment-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d comments" ]
      interval: 5s
      timeout: 5s
      retries: 10


  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_started
    ports:
      - "9090:9090"
    restart: on-failure
    environment:
      SERVER_PORT: 9090
      POSTGRES_HOST: stats-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


  user-service:
    build:
      context: .
      dockerfile: core/user-service/Dockerfile
    depends_on:
      user-db:
        condition: service_healthy
      config-server:
        condition: service_started
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


  request-service:
    build:
      context: .
      dockerfile: core/request-service/Dockerfile
    depends_on:
      request-db:
        condition: service_healthy
      config-server:
        condition: service_started
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://request-db:5432/requests
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


  event-service:
    build:
      context: .
      dockerfile: core/event-service/Dockerfile
    depends_on:
      event-db:
        condition: service_healthy
      config-server:
        condition: service_started
      stats-server:
        condition: service_started
      user-service:
        condition: service_started
      request-service:
        condition: service_started
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://event-db:5432/events
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


  comment-service:
    build:
      context: .
      dockerfile: core/comment-service/Dockerfile
    depends_on:
      comment-db:
        condition: service_healthy
      config-server:
        condition: service_started
      stats-server:
        condition: service_started
      user-service:
        condition: service_started
      event-service:
        condition: service_started
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://comment-db:5432/comments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


  gateway-server:
    build:
      context: .
      dockerfile: infra/gateway-server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - user-service
      - request-service
      - event-service
      - comment-service
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888


volumes:
  stats-db-data:
  user-db-data:
  request-db-data:
  event-db-data:
  comment-db-data:
